/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Random;
import java.util.Scanner;

public class App {
    Scanner input = new Scanner(System.in);
    Random rand = new Random();
    boolean gameState = true;
    int targetNumber;
    int score = 0;

    public void generateInt(){
        targetNumber = rand.nextInt(0, 100);
    }

    public void StartGame() {
        generateInt();
        System.out.println("Welcome to Number Guesser");
        System.out.println("Guess an integer between 0 and 100");
        while (gameState) {
            int guess = input.nextInt();
            input.nextLine();
            if (guess == targetNumber) {
                System.out.println("Correct guess!!!");
                System.out.println("Would you like to play again?, answer y/n");
                String replaystr = input.nextLine();
                if (replaystr.equalsIgnoreCase("y")) {
                    generateInt();
                    System.out.println("Starting again, guess an integer between 0 and 100");
                } else {
                    System.out.println("Ending game");
                    gameState = false;
                }
            }
            else if (guess < targetNumber) {
                System.out.println("You guess is too low");
            }
            else if (guess > targetNumber) {
                System.out.println("Your guess is too high");
            }
        }
    }

    public static void main(String[] args) {
        new App().StartGame();
    }
}
